import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styles from "../styles/Home.module.css";
import { io } from "socket.io-client";

const Home: NextPage = () => {
  useEffect(() => {
    const socket = io("https://thawing-ocean-76904.herokuapp.com/");
    socket.on("stream", (e) => {
      console.log(e);
    });
    socket.on("time", (e) => {
      console.log(e);
    });
    return () => {
      socket.disconnect();
    };
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      teste1
    </div>
  );
};

export default Home;
